-- Verified Mid-Atlantic riding locations, safe to re-run.
insert into public.riding_locations
  (location_key,name,access,kind,address,lat,lng,drive,details,requirements,link)
values
('wicomico-mx','Wicomico MX & ATV','paid','Tracks + trails','11100 Kingston Place, Charlotte Hall, MD 20622',38.4768,-76.8407,'~1.25 hr','300-acre bring-your-own-bike park with beginner, intermediate and advanced tracks plus about four miles of woods trails.','Dirt bikes/ATVs/UTVs; helmet and waiver required. Weather-dependent.','https://www.wicomicomx.com/'),
('the-cove','The Cove Campground','paid','Rocky mountain trails','980 Cove Road, Gore, VA 22637',39.2146,-78.3625,'~2.25 hr','Private mountain property west of Winchester with an ATV/moto trail system and camping.','Call ahead for current moto access, trail conditions and day-use pricing.','https://www.covecampground.com/'),
('taskers-gap','Taskers Gap OHV Trail System','free','Public OHV trails','Taskers Gap Trailhead, Edinburg, VA',38.8019,-78.5125,'~2.5 hr','Part of Virginia’s largest public OHV system; steep, rocky and narrow riding among former forest roads.','Low-cost OHV permit required; seasonal opening and spark-arrestor/vehicle rules apply.','https://www.fs.usda.gov/r08/gwj/recreation/peters-mill-runtaskers-gap-trail-system'),
('peters-mill','Peters Mill Run OHV Trail','free','Public OHV trail','Peters Mill Run North Trailhead, Edinburg, VA',38.8551,-78.5656,'~2.6 hr','The more approachable side of the 36-mile Peters Mill Run/Taskers Gap system, with scenic former forest-road terrain.','Low-cost OHV permit required; seasonal opening and Forest Service rules apply.','https://www.fs.usda.gov/r08/gwj/recreation/peters-mill-runtaskers-gap-trail-system'),
('aoaa','AOAA Trails','paid','Coal-country trail park','4100 State Route 125, Coal Township, PA 17866',40.7783,-76.4960,'~3.1 hr','Large Northumberland County trail system with terrain for motorcycles, ATVs, UTVs and full-size vehicles.','Daily or annual AOAA permit and waiver required; check operating calendar.','https://www.aoaatrails.com/getstarted'),
('famous-reading','Famous Reading Outdoors','paid','Coal-country trail network','200 Mahantongo Street, Pottsville, PA 17901',40.6856,-76.1955,'~3 hr','Thousands of acres and hundreds of miles of dirt-bike-friendly coal-country trails across multiple riding areas.','Annual membership generally required; guided tours and limited guest passes may be available.','https://readingoutdoors.com/'),
('mountain-ridge','Mountain Ridge ATV Park','paid','Trails + motocross','517 Boone Road, Central City, PA 15926',40.0529,-78.8583,'~3.5 hr','More than 100 miles of one-way trails on 2,500+ acres, plus motocross/kids tracks and camping.','Bring your own dirt bike; seasonal hours, pass and waiver apply.','https://mountainridgeatvtrails.com/'),
('rock-run','Rock Run Recreation Area','paid','Trails + single-track','1228 St. Lawrence Road, Patton, PA 16668',40.6335,-78.6379,'~3.8 hr','Large western Pennsylvania recreation area with a dedicated dirt-bike single-track network in addition to shared trails.','Pass and waiver required; verify seasonal calendar before travel.','https://www.rockrunrecreation.com/'),
('mines-meadows','Mines & Meadows','paid','Trails + single-track','1307 Old Route 18, Wampum, PA 16157',40.8887,-80.3406,'~4 hr','84+ miles of trails and eight miles of dirt-bike-only single-track, including guided underground mine riding.','Date-specific pass and online waiver; check the drive from your exact Maryland starting point.','https://minesandmeadows.com/')
on conflict (location_key) do update set
  name=excluded.name,access=excluded.access,kind=excluded.kind,address=excluded.address,
  lat=excluded.lat,lng=excluded.lng,drive=excluded.drive,details=excluded.details,
  requirements=excluded.requirements,link=excluded.link;
